<?php

namespace AppBundle\Repository;

/**
 * FioulPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FioulPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
