<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FioulPriceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FioulPriceRepository extends EntityRepository
{
    /**
     * @param string $zipCode
     * @param string $start
     * @param string $end
     * @return array
     */
    public function retrieveAmountFromZipCodeAndDate(string $zipCode, string $start, string $end): array
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.amount')
            ->where('p.zipCode = :zipCode')
            ->andWhere('p.date >= :startDate')
            ->andWhere('p.date <= :endDate')
            ->setParameter('zipCode', $zipCode)
            ->setParameter('startDate', $start)
            ->setParameter('endDate', $end)
            ->orderBy('p.amount', 'ASC')
            ->getQuery();

        $amounts = $query->getResult();

        return $amounts;
    }

    /**
     * @param string $zipCode
     * @param string $start
     * @param string $end
     * @return array
     */
    public function retrieveAmountAndDateFromZipCodeAndDate(string $zipCode, string $start, string $end): array
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.amount, p.date')
            ->where('p.zipCode = :zipCode')
            ->andWhere('p.date >= :startDate')
            ->andWhere('p.date <= :endDate')
            ->setParameter('zipCode', $zipCode)
            ->setParameter('startDate', $start)
            ->setParameter('endDate', $end)
            ->orderBy('p.amount', 'ASC')
            ->getQuery();

        $results = $query->getResult();

        return $results;
    }

    /**
     * @return array
     */
    public function retrieveZipCodes()
    {
        $query = $this->createQueryBuilder('p')
            ->select('DISTINCT p.zipCode')
            ->orderBy('p.zipCode', 'ASC')
            ->getQuery();

        $amounts = $query->getResult();

        return $amounts;
    }
}
